import { GiftItem } from './types';

export const INITIAL_GIFTS: GiftItem[] = [
  // Eletrodomésticos e Móveis
  { id: 'em-1', name: 'Liquidificador', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-2', name: 'Cafeteira', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-3', name: 'Sanduicheira', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-4', name: 'Batedeira', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-5', name: 'Processador de alimentos', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-6', name: 'Espremedor de frutas', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-7', name: 'Purificador/Filtro de água', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-8', name: 'Bebedouro', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-9', name: 'Sofá', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-10', name: 'Mesa de jantar', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-11', name: 'Cadeiras para mesa', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-12', name: 'Rack para TV', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-13', name: 'Guarda-roupa', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-14', name: 'Criado-mudo', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-15', name: 'Escrivaninha', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-16', name: 'Cadeira de escritório', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-17', name: 'Estante', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-18', name: 'Aparador', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },
  { id: 'em-19', name: 'Sapateira', category: '🏠 Eletrodomésticos e Móveis', status: 'available' },

  // Cozinha
  { id: 'coz-1', name: 'Jogo de panelas', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-2', name: 'Panela de pressão', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-3', name: 'Frigideiras', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-4', name: 'Assadeiras', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-5', name: 'Formas', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-6', name: 'Travessas', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-7', name: 'Refratários', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-8', name: 'Pratos', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-9', name: 'Pratos fundos', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-10', name: 'Pratos sobremesa', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-11', name: 'Tigelas', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-12', name: 'Copos', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-13', name: 'Taças', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-14', name: 'Canecas', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-15', name: 'Xícaras', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-16', name: 'Faqueiro', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-17', name: 'Facas', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-18', name: 'Conchas', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-19', name: 'Espátulas', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-20', name: 'Pegadores', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-21', name: 'Tábuas', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-22', name: 'Escorredor', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-23', name: 'Ralador', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-24', name: 'Abridor', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-25', name: 'Descascador', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-26', name: 'Potes', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-27', name: 'Jarras', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-28', name: 'Garrafa térmica', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-29', name: 'Porta-temperos', category: '🍳 Cozinha', status: 'available' },
  { id: 'coz-30', name: 'Lixeira', category: '🍳 Cozinha', status: 'available' },

  // Quarto
  { id: 'qua-1', name: 'Jogo de lençóis', category: '🛏 Quarto', status: 'available' },
  { id: 'qua-2', name: 'Fronhas', category: '🛏 Quarto', status: 'available' },
  { id: 'qua-3', name: 'Travesseiros', category: '🛏 Quarto', status: 'available' },
  { id: 'qua-4', name: 'Edredom', category: '🛏 Quarto', status: 'available' },
  { id: 'qua-5', name: 'Cobertor', category: '🛏 Quarto', status: 'available' },
  { id: 'qua-6', name: 'Colcha', category: '🛏 Quarto', status: 'available' },
  { id: 'qua-7', name: 'Mantas', category: '🛏 Quarto', status: 'available' },
  { id: 'qua-8', name: 'Cabides', category: '🛏 Quarto', status: 'available' },

  // Banheiro
  { id: 'ban-1', name: 'Toalhas', category: '🚿 Banheiro', status: 'available' },
  { id: 'ban-2', name: 'Tapetes', category: '🚿 Banheiro', status: 'available' },
  { id: 'ban-3', name: 'Cortina Box', category: '🚿 Banheiro', status: 'available' },
  { id: 'ban-4', name: 'Lixeira', category: '🚿 Banheiro', status: 'available' },
  { id: 'ban-5', name: 'Porta sabonete', category: '🚿 Banheiro', status: 'available' },
  { id: 'ban-6', name: 'Porta escovas', category: '🚿 Banheiro', status: 'available' },
  { id: 'ban-7', name: 'Cesto de roupas', category: '🚿 Banheiro', status: 'available' },

  // Sala
  { id: 'sal-1', name: 'Cortinas', category: '🛋 Sala', status: 'available' },
  { id: 'sal-2', name: 'Tapete', category: '🛋 Sala', status: 'available' },
  { id: 'sal-3', name: 'Almofadas', category: '🛋 Sala', status: 'available' },
  { id: 'sal-4', name: 'Mesa de centro', category: '🛋 Sala', status: 'available' },
  { id: 'sal-5', name: 'Mesa lateral', category: '🛋 Sala', status: 'available' },
  { id: 'sal-6', name: 'Luminária', category: '🛋 Sala', status: 'available' },

  // Lavanderia
  { id: 'lav-1', name: 'Varal', category: '🧺 Lavanderia', status: 'available' },
  { id: 'lav-2', name: 'Ferro', category: '🧺 Lavanderia', status: 'available' },
  { id: 'lav-3', name: 'Tábua', category: '🧺 Lavanderia', status: 'available' },
  { id: 'lav-4', name: 'Balde', category: '🧺 Lavanderia', status: 'available' },
  { id: 'lav-5', name: 'Vassoura', category: '🧺 Lavanderia', status: 'available' },
  { id: 'lav-6', name: 'Rodo', category: '🧺 Lavanderia', status: 'available' },
  { id: 'lav-7', name: 'Mop', category: '🧺 Lavanderia', status: 'available' },
  { id: 'lav-8', name: 'Pá', category: '🧺 Lavanderia', status: 'available' },
  { id: 'lav-9', name: 'Panos', category: '🧺 Lavanderia', status: 'available' },
  { id: 'lav-10', name: 'Esponjas', category: '🧺 Lavanderia', status: 'available' },

  // Diversos
  { id: 'div-1', name: 'Kit Ferramentas', category: '📦 Diversos', status: 'available' },
  { id: 'div-2', name: 'Filtro de Linha', category: '📦 Diversos', status: 'available' },
  { id: 'div-3', name: 'Extensão', category: '📦 Diversos', status: 'available' },
  { id: 'div-4', name: 'Escada', category: '📦 Diversos', status: 'available' },
  { id: 'div-5', name: 'Espelho', category: '📦 Diversos', status: 'available' },
  { id: 'div-6', name: 'Relógio', category: '📦 Diversos', status: 'available' },
  { id: 'div-7', name: 'Organizadores', category: '📦 Diversos', status: 'available' },
];
export const GIFT_CATEGORIES = [
  '🏠 Eletrodomésticos e Móveis',
  '🍳 Cozinha',
  '🛏 Quarto',
  '🚿 Banheiro',
  '🛋 Sala',
  '🧺 Lavanderia',
  '📦 Diversos'
];
